

services:
  # Front-end React
  client:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Backend Express + Node.js
  server:
    build:
      context: ./server
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ma_base_de_donnees
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    networks:
      - app-network

  # Base de données MariaDB
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ma_base_de_donnees
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

# Réseau commun pour les services
networks:
  app-network:
    driver: bridge

# Volume pour persister les données MariaDB
volumes:
  mariadb-data:
